name: OWASP ZAP DAST Scan

on:
  push:
    branches:
      - main

jobs:
  zap-dast:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      # Checkout Repository
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # Verify Target URL
      - name: Verify Target URL
        run: |
          echo "Scanning Target: ${{ secrets.TARGET_URL }}"
          curl -I "${{ secrets.TARGET_URL }}"

      # Create Report Directory
      - name: Create Report Directory
        run: |
          mkdir -p reports
          chmod -R 777 reports
          ls -ld reports

      # Pull Latest ZAP Docker Image
      - name: Pull OWASP ZAP Docker Image
        run: |
          docker pull ghcr.io/zaproxy/zaproxy:stable

      # Run OWASP ZAP Baseline Scan
      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/reports:/zap/wrk/:rw" \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t "${{ secrets.TARGET_URL }}" \
            -r zap-report.html \
            -J zap-report.json \
            -x zap-report.xml \
            -m 5 || true

      - name: Check ZAP Results
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

          echo "========== ZAP SUMMARY =========="

          HIGH=$(jq '[.site[].alerts[] | select(.riskcode=="3")] | length' reports/zap-report.json)
          MEDIUM=$(jq '[.site[].alerts[] | select(.riskcode=="2")] | length' reports/zap-report.json)
          LOW=$(jq '[.site[].alerts[] | select(.riskcode=="1")] | length' reports/zap-report.json)
          INFO=$(jq '[.site[].alerts[] | select(.riskcode=="0")] | length' reports/zap-report.json)

           echo "High Alerts   : $HIGH"
           echo "Medium Alerts : $MEDIUM"
           echo "Low Alerts    : $LOW"
           echo "Info Alerts   : $INFO"

           if [ "$HIGH" -gt 0 ]; then
           echo "❌ High-risk vulnerabilities found."
           exit 1
           fi

           echo "✅ No High-risk vulnerabilities found."

      - name: Show ZAP Findings
        run: |
          echo "========== ZAP Findings =========="

          jq -r '
          .site[].alerts[] |
          "-------------------------------------\n" +
          "Alert      : \(.alert)\n" +
          "Risk       : \(.riskdesc)\n" +
          "Confidence : \(.confidence)\n" +
          "Description: \(.desc)\n"
          ' reports/zap-report.json

      # Verify Reports
      - name: Verify Generated Reports
        if: always()
        run: |
          echo "===== Reports Directory ====="
          ls -lah reports

      # Upload Reports
      - name: Upload ZAP Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: OWASP-ZAP-Reports
          path: reports/

      # Show Workflow Summary
      - name: Scan Summary
        if: always()
        run: |
          echo "======================================"
          echo " OWASP ZAP Scan Completed"
          echo "======================================"
          echo "Target: ${{ secrets.TARGET_URL }}"
          echo "Reports Generated:"
          ls reports
