name: Node.js DevSecOps Pipeline

on:
  push:
    branches:
      - main
    paths: 
      - .github/workflows/Sast.yml
    
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    # Checkout
    - name: Checkout source code
      uses: actions/checkout@v4

    # Setup Node
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    # Install dependencies
    - name: Install dependencies
      run: npm install

    ###########################################################
    # SONARQUBE SAST
    ###########################################################

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
        args: >
          -Dsonar.projectKey=SAST-Project1
          -Dsonar.projectName=SAST-Project1
          -Dsonar.sources=.
          -Dsonar.sourceEncoding=UTF-8

    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    ###########################################################
    # WAIT FOR SONAR ANALYSIS
    ###########################################################

    - name: Wait for SonarQube Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |

        if [ ! -f ".scannerwork/report-task.txt" ]; then
          echo "report-task.txt not found"
          exit 1
        fi

        TASK_URL=$(grep ceTaskUrl .scannerwork/report-task.txt | cut -d '=' -f2-)

        STATUS="PENDING"

        while [[ "$STATUS" == "PENDING" || "$STATUS" == "IN_PROGRESS" ]]; do

          RESPONSE=$(curl -s -u ${SONAR_TOKEN}: "$TASK_URL")

          STATUS=$(echo "$RESPONSE" | jq -r '.task.status')

          echo "Analysis Status : $STATUS"

          sleep 5

        done

        if [[ "$STATUS" != "SUCCESS" ]]; then
          echo "Sonar Analysis Failed"
          exit 1
        fi

        ANALYSIS_ID=$(echo "$RESPONSE" | jq -r '.task.analysisId')

        echo "ANALYSIS_ID=$ANALYSIS_ID" >> $GITHUB_ENV

    ###########################################################
    # QUALITY GATE
    ###########################################################

    - name: Check Quality Gate
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |

        RESPONSE=$(curl -s -u ${SONAR_TOKEN}: \
        "${SONAR_HOST_URL}/api/qualitygates/project_status?analysisId=${ANALYSIS_ID}")

        echo "$RESPONSE" | jq .

        STATUS=$(echo "$RESPONSE" | jq -r '.projectStatus.status')

        echo "Quality Gate = $STATUS"

        echo "Failed Conditions"

        echo "$RESPONSE" | jq -r '
          .projectStatus.conditions[]
          | select(.status=="ERROR")
          | "\(.metricKey): \(.actualValue) Expected: \(.errorThreshold)"
        '

        if [[ "$STATUS" != "OK" ]]; then
          exit 1
        fi

    ###########################################################
    # EXPORT SONAR REPORT
    ###########################################################

    - name: Export SonarQube Issues
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |

        curl -u ${SONAR_TOKEN}: \
        "${SONAR_HOST_URL}/api/issues/search?componentKeys=SAST-Project1&ps=500" \
        -o sonar-report.json

        ls -lh sonar-report.json

    ###########################################################
    # UPLOAD SONAR REPORT TO DEFECTDOJO
    ###########################################################

    - name: Upload Sonar Report to DefectDojo
      run: |

        curl -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/reimport-scan/" \
        -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
        -F "scan_type=SonarQube Scan" \
        -F "engagement=${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}" \
        -F "file=@sonar-report.json" \
        -F "active=true" \
        -F "verified=true" \
        -F "close_old_findings=false"

  
###########################################################
# CREATE REPORT DIRECTORY
###########################################################

    - name: Create Reports Directory
      run: |
       mkdir -p ${{ github.workspace }}/reports
       chmod -R 777 ${{ github.workspace }}/reports

###########################################################
# RUN ZAP BASELINE SCAN
###########################################################

    - name: Run OWASP ZAP Baseline Scan
      run: |
       mkdir -p reports

       EXIT_CODE=0

       docker run --rm \
        -v "${{ github.workspace }}/reports:/zap/wrk:rw" \
        ghcr.io/zaproxy/zaproxy:stable \
        zap-baseline.py \
        -t "${{ secrets.TARGET_URL }}" \
        -x zap-report.xml \
        -J zap-report.json \
        -r zap-report.html || EXIT_CODE=$?

         echo "ZAP Exit Code: $EXIT_CODE"

        # Ignore warnings only
          if [ "$EXIT_CODE" -eq 2 ]; then
          echo "Warnings found. Continuing..."
          exit 0
          fi

          exit $EXIT_CODE

###########################################################
# VERIFY REPORTS
###########################################################

    - name: Verify Generated Reports
      run: |
        ls -lah ${{ github.workspace }}/reports

###########################################################
# UPLOAD REPORTS AS ARTIFACT
###########################################################

    - name: Upload ZAP Reports
      uses: actions/upload-artifact@v4
      with:
       name: zap-reports
       path: |
         reports/zap-report.html
         reports/zap-report.xml
         reports/zap-report.json

  ###########################################################
  # IMPORT INTO DEFECTDOJO
  ###########################################################

    - name: Upload ZAP Report to DefectDojo
      run: |
        curl -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/reimport-scan/" \
        -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
        -F "scan_type=ZAP Scan" \
        -F "engagement=${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}" \
        -F "file=@${{ github.workspace }}/reports/zap-report.xml" \
        -F "active=true" \
        -F "verified=true" \
        -F "close_old_findings=false"
